// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'game': string;
  'menu': string;
  'showKey': string;
  'timer': string;
  'waiting': string;
}
export const cssExports: CssExports;
export default cssExports;
